/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */
import axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

export interface Pet {
  id: number;
  nome: string;
  raca: string;
  idade: number;
}

export interface InserePetValidator {
  nome: string;
  raca: string;
  idade: number;
  id: number;
}

export const getPets = <TData = AxiosResponse<Pet[]>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/pets`,options
    );
  }

export const postPet = <TData = AxiosResponse<Pet>>(
    inserePetValidator: InserePetValidator, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/pet`,
      inserePetValidator,options
    );
  }

export type GetPetsResult = AxiosResponse<Pet[]>
export type PostPetResult = AxiosResponse<Pet>
